In [51]:
import numpy as np

In [52]:
a=np.array([1,2,3,4])
type(a)


numpy.ndarray

In [53]:

#one dimensional
a

array([1, 2, 3, 4])

In [54]:
#whole willl be in string now
np.array([1,2,3,"allit",4+8j])

array(['1', '2', '3', 'allit', '(4+8j)'], dtype='<U64')

In [55]:
#whole data in floating
np.array([1,2,3.5,5.6])

array([1. , 2. , 3.5, 5.6])

In [56]:
#two dimensional
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [57]:
#apmne hisab se list bna diya
np.array([[1,2],[3,4],[6,7,8]])

C:\Users\lalit\AppData\Local\Temp\ipykernel_35160\1237775334.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2],[3,4],[6,7,8]])


array([list([1, 2]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [58]:
#theree dimensional due to]]] --important
np.array([[[1,2],[3,4]],[[1,3],[3,4]]])

array([[[1, 2],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [59]:
#3dim
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [60]:
#conevrting data into complex

In [61]:
np.array([1,2,3],dtype=complex)


array([1.+0.j, 2.+0.j, 3.+0.j])

In [62]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [63]:
#intuple also   data can contains
np.array([(91,2),(3,4)])

array([[91,  2],
       [ 3,  4]])

In [64]:
np.array([(1,2),(4,5)],dtype=[("a","<i2"),("b","<i8")])

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [65]:
#i2,i4,i8 for byte momory
arr=np.array([(1,2),(4,5)],dtype=[("a","<i2"),("b","<i8")])

In [66]:
arr[0][0]

1

In [67]:
type(arr[0][0])

numpy.int16

In [68]:
arr[0][1]

2

In [69]:
type(arr[0][1])

numpy.int64

In [70]:
arr=np.array([[1,2],[3,4]])

In [71]:
arr

array([[1, 2],
       [3, 4]])

In [72]:
arr[0][1]

2

In [73]:
type(arr[0][1])

numpy.int32

In [74]:
#to convert into matrix
mat=np.mat(arr)

In [75]:
l=[3,4,5,76,7]

In [76]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [77]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [78]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [79]:
#matric will remain matrix here
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [80]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [81]:
#for checking matrix is also a subset of array
issubclass(np.matrix,np.ndarray)

True

In [82]:
issubclass(np.ndarray,np.matrix)

False

In [83]:
arr

array([[1, 2],
       [3, 4]])

In [84]:
#a is a shollow copy
a=arr

In [85]:
#b is a deep copy
b=np.copy(arr)

In [86]:
b

array([[1, 2],
       [3, 4]])

In [87]:
#array is a mutable , it can be changed later
arr[0][0]=67

In [88]:
#base ko change karne par cop wala change nahi hota , sirf = wala hota hai|
a

array([[67,  2],
       [ 3,  4]])

In [89]:
b

array([[1, 2],
       [3, 4]])

In [90]:
arr[0:1]

array([[67,  2]])

In [91]:
#it will give last row
arr[-1]

array([3, 4])

In [92]:
#last row ka first elemnent
arr[-1,0]

3

In [93]:
#first row ka last element
arr[0,-1]

2

In [94]:
for i in arr:
    print (i)

[67  2]
[3 4]


In [95]:
#np.fromfunction(function,shape)
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [96]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [97]:
#iki power j
np.fromfunction(lambda i , j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [98]:
1/0

ZeroDivisionError: division by zero

In [99]:
np.fromfunction(lambda i , j :i/j,(3,3))

C:\Users\lalit\AppData\Local\Temp\ipykernel_35160\2281161872.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))
C:\Users\lalit\AppData\Local\Temp\ipykernel_35160\2281161872.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [100]:
gen=(i*i for i in range(5) )
gen

<generator object <genexpr> at 0x00000213D8FD4970>

In [101]:
[i*i for i in range(5) ]

[0, 1, 4, 9, 16]

In [102]:
def test(x):
    yield x

In [103]:
test(5)

<generator object test at 0x00000213D8FD4D60>

In [104]:
#extracting from generator
gen=(i*i for i in range(5) )
gen
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [105]:


#extracting from generator
#
#gen=(i*i for i in range(5) )
#gen
gen=range(5)
for i in gen:
    print(i)
np.fromiter(gen,dtype=int)

0
1
2
3
4


array([0, 1, 2, 3, 4])

In [106]:
np.fromstring("1,2,3,4",sep=",",dtype=int)

array([1, 2, 3, 4])

In [107]:
#to make complex
np.fromstring("45 55 33",sep=" ",dtype=complex)

array([45.+0.j, 55.+0.j, 33.+0.j])

In [108]:
#all these are from numpy are ndarray type

In [109]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [110]:
#to find dimension:
arr1.ndim

2

In [111]:
arr1.size

12

In [112]:
arr1.shape

(3, 4)

In [113]:
arr=np.array(l,dtype=int)
arr

array([ 3,  4,  5, 76,  7])

In [114]:
#one dimensional
arr.ndim

1

In [115]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [116]:
arr2.size

16

In [117]:
arr2.ndim

3

In [118]:
#2-data , with (2,4) shape
arr2.shape

(2, 2, 4)

In [119]:
#now changing with some mid bracket removing (3d data with one layer of two d data-it should have one more separation bracket)
arr2 = np.array([[[1,2,3,4],[4,5,6,7],[1,2,3,4],[4,5,6,7]]])
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7],
        [1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [120]:
arr2.size

16

In [121]:
arr2.ndim

3

In [122]:
arr2.shape

(1, 4, 4)

In [123]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
#but with numy
np.arange(6.6)

In [ ]:
 #IT INCLUDES UPPER BoUND HERE becaiuse of floating decimals
np.arange(6.6,9,0.3)

In [ ]:
np.arange(9,6.6,-0.3)

In [ ]:
#no issue of upper bound exclusion here and - not required for reverse
np.linspace(1,2,5)
#it gives 5 data between 1-2 equally

In [ ]:
np.linspace(0.1,.11,5)

In [ ]:
np.linspace(0.3,.1,4)

In [ ]:
np.zeros(4)

In [ ]:
a=np.zeros((4,2))

In [ ]:
np.zeros((3,5,4))


In [124]:
np.zeros((2,5,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [125]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [126]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [127]:
np.ones((2,3,4))+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [128]:
np.empty(4)

array([1. , 0.5, 2. , 1. ])

In [129]:
#se a single pair of parentheses for 1D shapes (e.g., np.empty(4)).
#Use nested parentheses for multi-dimensional shapes (e.g., np.empty((3, 4))).
np.empty((3,4))

array([[1.12855279e-311, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.10343781e-312, 6.82116729e-043, 4.27090684e-090,
        1.56082908e+161],
       [8.40872116e+164, 6.95494650e-042, 6.48224659e+170,
        4.93432906e+257]])

In [130]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [131]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [132]:
#from 2to 4 in 4 equal parts
np.linspace(2,4,4,endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [133]:
    np.linspace([1,6],4,endpoint=False,axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [134]:
    np.linspace([1,6],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [135]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [136]:
np.logspace([2],[3],axis=0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [137]:
#important
d=np.linspace(3,7,40)
d

array([3.        , 3.1025641 , 3.20512821, 3.30769231, 3.41025641,
       3.51282051, 3.61538462, 3.71794872, 3.82051282, 3.92307692,
       4.02564103, 4.12820513, 4.23076923, 4.33333333, 4.43589744,
       4.53846154, 4.64102564, 4.74358974, 4.84615385, 4.94871795,
       5.05128205, 5.15384615, 5.25641026, 5.35897436, 5.46153846,
       5.56410256, 5.66666667, 5.76923077, 5.87179487, 5.97435897,
       6.07692308, 6.17948718, 6.28205128, 6.38461538, 6.48717949,
       6.58974359, 6.69230769, 6.79487179, 6.8974359 , 7.        ])

In [138]:
d.ndim

1

In [139]:
# to change dimensionality(earlier it was only 40 no.s), now 40 rows with one column
d.reshape(40,1)

array([[3.        ],
       [3.1025641 ],
       [3.20512821],
       [3.30769231],
       [3.41025641],
       [3.51282051],
       [3.61538462],
       [3.71794872],
       [3.82051282],
       [3.92307692],
       [4.02564103],
       [4.12820513],
       [4.23076923],
       [4.33333333],
       [4.43589744],
       [4.53846154],
       [4.64102564],
       [4.74358974],
       [4.84615385],
       [4.94871795],
       [5.05128205],
       [5.15384615],
       [5.25641026],
       [5.35897436],
       [5.46153846],
       [5.56410256],
       [5.66666667],
       [5.76923077],
       [5.87179487],
       [5.97435897],
       [6.07692308],
       [6.17948718],
       [6.28205128],
       [6.38461538],
       [6.48717949],
       [6.58974359],
       [6.69230769],
       [6.79487179],
       [6.8974359 ],
       [7.        ]])

In [140]:
d.reshape(1,4,10)
# the array can be interpreted as two arrays, each with one row and 20 columns.

array([[[3.        , 3.1025641 , 3.20512821, 3.30769231, 3.41025641,
         3.51282051, 3.61538462, 3.71794872, 3.82051282, 3.92307692],
        [4.02564103, 4.12820513, 4.23076923, 4.33333333, 4.43589744,
         4.53846154, 4.64102564, 4.74358974, 4.84615385, 4.94871795],
        [5.05128205, 5.15384615, 5.25641026, 5.35897436, 5.46153846,
         5.56410256, 5.66666667, 5.76923077, 5.87179487, 5.97435897],
        [6.07692308, 6.17948718, 6.28205128, 6.38461538, 6.48717949,
         6.58974359, 6.69230769, 6.79487179, 6.8974359 , 7.        ]]])

In [141]:
#on the basis normal distribution
np.random.rand(3)

array([0.07585531, 0.95821775, 0.61488867])

In [142]:
#on the basis standar normal distribution-mean 0,and std.=1.
np.random.randn(3)

array([1.33620644, 1.71687457, 1.32082674])

In [143]:
np.random.randn(2,2,3)

array([[[-1.28215117, -0.95050455,  0.532629  ],
        [ 2.33827349,  0.4285238 , -0.31325108]],

       [[ 0.44412091,  1.13598766,  0.116724  ],
        [ 1.8096317 ,  1.69397116, -0.41458817]]])

In [144]:
#data between only
np.random.randint(5,20)

15

In [145]:
# this is different,any data between 5-20 with 6 rows and 7columns
np.random.randint(5,20,(6,7))

array([[11, 18, 16,  7,  9, 10, 18],
       [12, 16, 19, 17, 12, 14, 15],
       [11, 16,  8,  7, 12, 16, 15],
       [13, 14,  8, 11,  9,  6, 16],
       [14, 19,  7,  7, 12, 15, 12],
       [16,  6, 11, 11,  6, 18, 12]])

In [146]:
#two arrays containing 2two rows and 3 column data
np.random.randn(2,2,3)

array([[[-0.23621638,  0.98438006, -0.83293659],
        [ 0.7267046 ,  0.1124167 ,  2.42916166]],

       [[ 0.06600945,  0.09583652, -1.85999822],
        [ 0.6699744 , -0.59351595, -0.66220447]]])

In [147]:
arr=np.random.randint(3,9,(3,3))
arr

array([[3, 5, 6],
       [6, 4, 4],
       [7, 5, 8]])

In [148]:
arr.reshape(1,9)

array([[3, 5, 6, 6, 4, 4, 7, 5, 8]])

In [149]:
#to create in 3d
arr.reshape(1,9,1)

array([[[3],
        [5],
        [6],
        [6],
        [4],
        [4],
        [7],
        [5],
        [8]]])

In [150]:
arr.reshape(3,3,1)

array([[[3],
        [5],
        [6]],

       [[6],
        [4],
        [4]],

       [[7],
        [5],
        [8]]])

In [155]:
#if don't want to give all axis for reshape  by checking multiply, then use one axis asnegative.
arr.reshape(3,-1809897)

array([[3, 5, 6],
       [6, 4, 4],
       [7, 5, 8]])

In [157]:
#this a trick
arr.reshape(1,-1372348734)

array([[3, 5, 6, 6, 4, 4, 7, 5, 8]])

In [158]:
arr.max()

8

In [159]:
arr.min()

3

In [166]:
arr=np.random.randint(4,100,(5,5)) 
arr

array([[77, 43, 48, 92, 46],
       [51, 26, 76, 25, 25],
       [63, 23, 68, 50, 38],
       [99, 64, 61, 94,  5],
       [10, 14, 97, 47, 84]])

In [167]:
arr[3:,3:]

array([[94,  5],
       [47, 84]])

In [169]:
arr[0:,1]
##or, arr[:,1]

array([43, 26, 23, 64, 14])

In [171]:

#twocolumns wii
#suppose want to extract column2 and column4 whole
arr[:,[1,3]]

array([[43, 92],
       [26, 25],
       [23, 50],
       [64, 94],
       [14, 47]])

In [172]:
arr

array([[77, 43, 48, 92, 46],
       [51, 26, 76, 25, 25],
       [63, 23, 68, 50, 38],
       [99, 64, 61, 94,  5],
       [10, 14, 97, 47, 84]])

In [175]:
arr[arr>10]

array([77, 43, 48, 92, 46, 51, 26, 76, 25, 25, 63, 23, 68, 50, 38, 99, 64,
       61, 94, 14, 97, 47, 84])

In [176]:
arr*arr

array([[5929, 1849, 2304, 8464, 2116],
       [2601,  676, 5776,  625,  625],
       [3969,  529, 4624, 2500, 1444],
       [9801, 4096, 3721, 8836,   25],
       [ 100,  196, 9409, 2209, 7056]])

In [178]:
arr1=np.random.randint(2,4,(3,3))
arr1

array([[3, 2, 3],
       [2, 3, 3],
       [3, 3, 3]])

In [190]:
arr2=np.random.randint(2,4,(3,2))
arr2

array([[2, 2],
       [2, 2],
       [3, 2]])

In [191]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [193]:
#matrix multiplication diff from plain multiplicatyion
arr1@arr2

array([[19, 16],
       [19, 16],
       [21, 18]])

In [ ]:

#for matrix multiplication suppose data is 3*2 and another is 3*3 can't be matrix multplied because column of a != row of b.(2=3)


In [194]:
arr/0

C:\Users\lalit\AppData\Local\Temp\ipykernel_35160\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [195]:
arr1**2

array([[9, 4, 9],
       [4, 9, 9],
       [9, 9, 9]], dtype=int32)

In [201]:
np.zeros(3,4)
#because it will start considering 4 as data type

TypeError: Cannot interpret '4' as a data type

In [217]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [218]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [219]:
#kind of braodcast adding a row straingt to the matrix, this is the row wise broadcasting
a+arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [220]:
#suppose if, then  broadcasting not possible
a= np.array([1,2,3])

In [221]:
arr+a

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [227]:
#now column wise broadcasting
b=np.array([1,2,3])


In [232]:
b.reshape(3,1)+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [234]:
#to use transpose HAVe to convert in 2D
b=np.array([[1,2,3]])

In [235]:
b.T

array([[1],
       [2],
       [3]])

In [237]:
arr = np.random.rand(5,4)
arr

array([[0.67812747, 0.88047717, 0.85446916, 0.73529708],
       [0.57834829, 0.38081293, 0.06944649, 0.45124419],
       [0.84259955, 0.43525975, 0.11866233, 0.37049349],
       [0.30296763, 0.98278815, 0.6228088 , 0.35380287],
       [0.28477856, 0.08649925, 0.16380965, 0.99766681]])

In [239]:
#for sqrt:
np.sqrt(arr)

array([[0.82348496, 0.93833745, 0.92437501, 0.85749465],
       [0.76049214, 0.61710042, 0.26352702, 0.67174712],
       [0.91793221, 0.65974218, 0.34447399, 0.60868176],
       [0.55042495, 0.99135672, 0.78918236, 0.59481331],
       [0.53364647, 0.29410755, 0.40473405, 0.99883273]])

In [240]:

#for exponential
np.exp(arr)

array([[1.97018505, 2.4120504 , 2.35012651, 2.08610164],
       [1.78309085, 1.4634738 , 1.0719147 , 1.57026467],
       [2.32239632, 1.54536441, 1.12598964, 1.44844923],
       [1.35387063, 2.67189551, 1.86415674, 1.42447435],
       [1.32946759, 1.09035055, 1.17799006, 2.71194696]])

In [241]:
np.log10(arr)

array([[-1.68688660e-01, -5.52818980e-02, -6.83036074e-02,
        -1.33537157e-01],
       [-2.37810542e-01, -4.19288319e-01, -1.15834968e+00,
        -3.45588380e-01],
       [-7.43787778e-02, -3.61251494e-01, -9.25687138e-01,
        -4.31219420e-01],
       [-5.18603777e-01, -7.54008954e-03, -2.05645258e-01,
        -4.51238651e-01],
       [-5.45492715e-01, -1.06298764e+00, -7.85660522e-01,
        -1.01447390e-03]])

In [243]:
arr1=np.random.randint(2,5,(5,5))
arr1

array([[2, 4, 2, 4, 3],
       [2, 3, 4, 2, 4],
       [3, 2, 4, 3, 3],
       [3, 2, 2, 3, 2],
       [4, 3, 4, 2, 3]])

In [244]:
np.log10(arr1)

array([[0.30103   , 0.60205999, 0.30103   , 0.60205999, 0.47712125],
       [0.30103   , 0.47712125, 0.60205999, 0.30103   , 0.60205999],
       [0.47712125, 0.30103   , 0.60205999, 0.47712125, 0.47712125],
       [0.47712125, 0.30103   , 0.30103   , 0.47712125, 0.30103   ],
       [0.60205999, 0.47712125, 0.60205999, 0.30103   , 0.47712125]])

In [255]:
np.random.seed(20)
np.random.rand(2,4)

array([[0.5881308 , 0.89771373, 0.89153073, 0.81583748],
       [0.03588959, 0.69175758, 0.37868094, 0.51851095]])